/- Root module: imports every live file under EM/.

The verified set is exactly this import closure: no `sorry`, no user axioms, no
`native_decide`; every published declaration depends only on `propext`, `Classical.choice`,
`Quot.sound` (gate: `python3 tools/check_axioms.py`, run after `lake build`).
This module depends only on Mathlib.  The registry tooling (`EM/Meta/{Registry,Blueprint}.lean`,
which need CA / LeanArchitect) is the separate library `EMRegistry` (root `EMRegistry.lean`),
built by `lake build` as well. The ONLY files under EM/ deliberately excluded are those in
EM/Archive/ — retired mathematics kept for reference, with proof bodies
stubbed behind `#exit` or preserved whole-file; see EM/Archive/README.md.
`tools/gen_codebase_table.py` audits this: it warns when a live file is
missing from the paper's codebase table, which is generated from the
same active-file set. -/
import EM.Adelic.Equidist
import EM.Adelic.Profinite
import EM.Adelic.ProfiniteGeneration
import EM.Adelic.UniformConductor
import EM.CME.Decomposition
import EM.CME.FiberAnalysis
import EM.CME.Reduction
import EM.CME.Equivalences
import EM.ForMathlib.VanDerCorput
import EM.ForMathlib.ZModDftParseval
import EM.ForMathlib.CoprimeAffineBlock
import EM.ForMathlib.PeriodicDensity
import EM.ForMathlib.CharNormOne
import EM.CME.Variants
import EM.Core.Conjectures
import EM.Core.Defs
import EM.Core.Euclid
import EM.Core.ResidueWalk
import EM.Ensemble.BagArithmetic
import EM.Ensemble.BaseCase
import EM.Ensemble.CRT
import EM.Ensemble.CRTFreedom
import EM.Ensemble.Decorrelation
import EM.Ensemble.EM
import EM.Ensemble.FiberAutonomy
import EM.Ensemble.FirstMoment
import EM.Ensemble.MinFacShifted
import EM.Ensemble.GenEM
import EM.Ensemble.MixedEnsemble
import EM.Ensemble.PT
import EM.Ensemble.Structure
import EM.Ensemble.TwoPointEnsemble
import EM.Ensemble.UnconditionalPSCD
import EM.Ensemble.UncenteredRefutations
import EM.Ensemble.WeylChain
import EM.Equidist.Bootstrap
import EM.Equidist.CharPRE
import EM.Equidist.CofinalOrbit
import EM.Equidist.Fourier
import EM.Equidist.FourierB
import EM.Equidist.OrbitAnalysis
import EM.Equidist.Preamble
import EM.Equidist.SelfAvoidance
import EM.Equidist.SelfCorrecting
import EM.Equidist.Sieve
import EM.Equidist.SieveTransfer
import EM.Equidist.Threshold
import EM.Equidist.OneHorizon
import EM.Equidist.WeakHitting
import EM.FunctionField.Analog
import EM.FunctionField.AutonomousMap
import EM.FunctionField.Bootstrap
import EM.FunctionField.DegreeTelescope
import EM.FunctionField.DensityMC
import EM.FunctionField.FFCharacterSums
import EM.FunctionField.FFSieve
import EM.FunctionField.FactorTree
import EM.FunctionField.Finiteness
import EM.FunctionField.IrreducibilityDensity
import EM.FunctionField.Master
import EM.FunctionField.MultiplierCCSB
import EM.FunctionField.NecklaceFormula
import EM.FunctionField.OrbitBarrier
import EM.FunctionField.PopulationEquidist
import EM.FunctionField.StableTower
import EM.FunctionField.StochasticMC
import EM.FunctionField.SubgroupEscape
import EM.FunctionField.WeakMC
import EM.GaussEM.GaussConfinement
import EM.GaussEM.GaussEMDefs
import EM.GaussEM.GaussWalkStructure
import EM.Group.Bridge
import EM.Group.CRT
import EM.Group.Core
import EM.Group.CyclicWalkCoverage
import EM.Group.DepartureGraph
import EM.Group.Escape
import EM.Group.QR
import EM.Group.RotorRouter
import EM.Group.SEInstances
import EM.IK.AbelChain
import EM.IK.Karamata
import EM.IK.Ch1
import EM.IK.Ch2
import EM.IK.Ch3
import EM.IK.Ch4
import EM.IK.Ch5
import EM.IK.Ch7AdditiveLS
import EM.IK.Ch7CesaroChain
import EM.IK.Ch7Foundations
import EM.IK.Ch7Hilbert
import EM.IK.Ch7HilbertB
import EM.IK.Ch7MultiplicativeLS
import EM.IK.Ch7SieveApplications
import EM.IK.Ch7SieveCRT
import EM.IK.DirichletDensity
import EM.IK.Tauberian
import EM.LargeSieve.Analytic
import EM.LargeSieve.Basic
import EM.LargeSieve.Harmonic
import EM.LargeSieve.PrimeArithLS
import EM.LargeSieve.Spectral
import EM.LargeSieve.Structural
import EM.LargeSieve.WalkAnalysis
import EM.LargeSieve.WalkDecomposition
import EM.Meta.DeadEnds
import EM.Meta.OrbitBarrier
import EM.Meta.BagInformation
import EM.Meta.Diamonds
import EM.Meta.Dobrushin
import EM.Meta.LFunction
import EM.Meta.MarkovSieve
import EM.Obstruction.Anatomy
import EM.Obstruction.Calculus
import EM.Obstruction.Fragment
import EM.Obstruction.MaxVariant
import EM.Obstruction.NoInvariant
import EM.Obstruction.RuleTransition
import EM.Population.AutonomousBranch
import EM.Population.AvoidanceTube
import EM.Population.ArborealTower
import EM.Population.BackwardLevels
import EM.Population.BackwardOrbit
import EM.Population.CompositeFloor
import EM.Population.DefectTelescope
import EM.Population.HeadDomination
import EM.Population.SeededGrowth
import EM.Population.BagConditionedLaw
import EM.Population.GrowthDensity
import EM.Population.SizeResidueDecoupling
import EM.Population.RelativeSize
import EM.Population.HittingSetStructure
import EM.Population.InfiniteM
import EM.Population.LSPlus
import EM.Population.LemmaD
import EM.Population.LemmaDBox
import EM.Population.LargeStepRoughness
import EM.Population.MertensLower
import EM.Population.ProfiniteDynamics
import EM.Population.ProfiniteEnsemble
import EM.Population.ProfiniteHeadline
import EM.Population.ReciprocalSum
import EM.Population.RigidityMaster
import EM.Population.SeedCapture
import EM.Population.SeedTypes
import EM.Population.SelectionLaw
import EM.Population.SylvesterTower
import EM.Population.SpectralConspiracy
import EM.Population.TailEstimate
import EM.Population.TailAssembly
import EM.Population.TheoremC
import EM.Population.FiberTheoremC
import EM.Population.AlmostAllDensity
import EM.Population.GrowingRange
import EM.Population.ProfiniteAttractor
import EM.Population.GrandOrbit
import EM.Population.AdelicShadow
import EM.Population.SquarefreeSeed
import EM.Population.AlmostAllGenMC
import EM.Population.TransferStrategy
import EM.Population.TreeChernoff
import EM.Population.TypeBadSmall
import EM.Population.WeakErgodicity
import EM.Population.WeakMullin
import EM.Reciprocity.SymbolAlgebra
import EM.Reciprocity.NoReciprocityInvariant
import EM.Reduction.DSLInfra
import EM.Reduction.Master
import EM.Reduction.SMSB
import EM.Reduction.SelfCorrecting
import EM.Reduction.ShiftedDensity
import EM.Reduction.TailIdentity
import EM.Reduction.TailWindow
import EM.Reduction.VisitEquidist
import EM.Reduction.WeakRecurrence
import EM.SDDS.Bridge
import EM.SDDS.Dynamics
import EM.SDDS.Reduction
import EM.Stochastic.DenseCapture
import EM.Stochastic.DiverseStepsToCapture
import EM.Stochastic.EpsilonDegeneration
import EM.Stochastic.EpsilonWalk
import EM.Stochastic.FactorDiversity
import EM.Stochastic.GeometricCapture
import EM.Stochastic.IteratedProductCoverage
import EM.Stochastic.MissedPrimes
import EM.Stochastic.MixedMC
import EM.Stochastic.MixedWalk
import EM.Stochastic.NonFaithfulCharacterEscape
import EM.Stochastic.PathMeasure
import EM.Stochastic.PerpetualPrimality
import EM.Stochastic.PositiveProbCapture
import EM.Stochastic.RandomFactorMC
import EM.Stochastic.RandomTwoPointMC
import EM.Stochastic.RandomTwoPointMCB
import EM.Stochastic.RandomVariant
import EM.Stochastic.ReachableSets
import EM.Stochastic.StochasticEM
import EM.Stochastic.ThreeAlmostSure
import EM.Stochastic.TransitionKernel
import EM.Stochastic.TreeSieveDecay
import EM.Stochastic.VanishingNoise
import EM.Stochastic.VanishingNoiseB
import EM.Stochastic.VanishingNoiseC
import EM.Stochastic.VanishingNoiseVariant
import EM.Stochastic.VanishingNoiseVariantB
import EM.Stochastic.VanishingNoiseVariantC
import EM.Transfer.CRTFiber
import EM.Transfer.CRTPointwise
import EM.Transfer.Excursion
import EM.Transfer.IntegerDioph
import EM.Transfer.SieveConstraint
import EM.Transfer.Substitution
