import EM.CME.Reduction
import EM.Equidist.Bootstrap
import EM.Group.CRT
import EM.Group.CyclicWalkCoverage

/-!
# The orbit-specificity barrier, with witnesses

Dead Ends #90 (population ≠ orbit) and #117 (multiplier cancellation ≠ walk cancellation)
carry the whole "why Mullin's conjecture is hard" thesis of this project, and until now
neither had a formal witness: the catalogue in `EM/Meta/DeadEnds.lean` listed `—` for both,
so every machine-checked dead end was a peripheral one.  This file supplies the witnesses,
and assembles them with the proved reductions into the integer analogue of
`EM/FunctionField/OrbitBarrier.lean`'s `orbit_barrier_thesis`.

Both witnesses are finite computations in `(ZMod 5)ˣ`, which is cyclic of order `4`
generated by `2`.  Two periodic multiplier sequences do all the work:

* `mulA` — period `(2,2,3,3)`, whose walk is `1, 2, 4, 2, 1, …` and **hits** `-1 = 4`;
* `mulB` — period `(2,3,2,3)`, whose walk is `1, 2, 1, 2, …` and **never** hits `4`.

`mulB` is a rearrangement of `mulA`: in every window of four consecutive steps both use
the multiplier `2` exactly twice and `3` exactly twice (`block_counts_agree`).  So the two
have *identical* empirical multiplier distributions and opposite hitting behaviour.  That
is Dead End #90 as a theorem rather than a slogan: population statistics do not determine
whether the orbit hits `-1`, and `-1` is exactly the death class
(`MullinGroup.walkZ_eq_neg_one_iff`), so they do not determine Mullin's conjecture.

The same `mulB` witnesses #117.  Let `chi5` be the order-4 character with `χ(2) = i`, so
`χ(3) = i³ = -i`.  The multipliers alternate `2, 3`, so their character sum alternates
`i, -i` and stays **bounded**; the walk alternates `1, 2`, so its character sum is
`M · (1 + i)` after `2M` steps and grows **linearly**.  Multiplier cancellation therefore
does not force walk cancellation, and `chi5` satisfies exactly the side conditions the
repository's own `MultCancelToWalkCancel` carries (`normSq ≤ 1`, `χ 0 = 0`, `∑_a χ a = 0`)
— so #117 is not an artifact of a sloppily stated hypothesis.

`mulB` is additionally a witness for #20/#130 in multiplicative form: its multipliers
`{2,3}` **generate** `(ZMod 5)ˣ` (`multipliers_generate`), yet the walk visits only
`{1,2}`.  Generation is not coverage; `SubgroupEscape` cannot close the gap.

## Main results

* `population_does_not_determine_hitting` — Dead End #90.
* `mult_cancel_not_walk_cancel` — Dead End #117.
* `integer_orbit_barrier_thesis` — the assembly: the two witnesses together with the
  proved reductions (`DH → MC`, `CME → CCSB → MC`, `HH → MC`) and the two proved
  structural inputs (`PRE`/SubgroupEscape, CRT position-blindness) that make
  orbit-specificity the *sole* remaining gap.
-/

noncomputable section

open Mullin Euclid MullinGroup

namespace OrbitBarrier

/-! ## Part 1: Two multiplier sequences with the same statistics -/

/-- Multiplier sequence `A`: period `(2, 2, 3, 3)`. -/
def mulA (k : ℕ) : ℕ := if k % 4 = 0 ∨ k % 4 = 1 then 2 else 3

/-- Multiplier sequence `B`: period `(2, 3, 2, 3)` — a rearrangement of `A`. -/
def mulB (k : ℕ) : ℕ := if k % 2 = 0 then 2 else 3

theorem mulA_periodic (N j : ℕ) : mulA (4 * N + j) = mulA j := by
  have h : (4 * N + j) % 4 = j % 4 := by omega
  simp only [mulA, h]

theorem mulB_periodic (N j : ℕ) : mulB (4 * N + j) = mulB j := by
  have h : (4 * N + j) % 2 = j % 2 := by omega
  simp only [mulB, h]

theorem mulA_mem (k : ℕ) : mulA k = 2 ∨ mulA k = 3 := by
  unfold mulA; split_ifs <;> simp

theorem mulB_mem (k : ℕ) : mulB k = 2 ∨ mulB k = 3 := by
  unfold mulB; split_ifs <;> simp

/-- Both multipliers are prime at every step (the EM multipliers are primes). -/
theorem mulA_prime (k : ℕ) : Nat.Prime (mulA k) := by
  rcases mulA_mem k with h | h <;> rw [h] <;> decide

theorem mulB_prime (k : ℕ) : Nat.Prime (mulB k) := by
  rcases mulB_mem k with h | h <;> rw [h] <;> decide

/-- **Identical empirical distributions.**  In every window of four consecutive steps,
`A` and `B` use each multiplier value the same number of times.  `B` is a rearrangement
of `A`, so no statistic of the multiplier population can distinguish them. -/
theorem block_counts_agree (N v : ℕ) :
    ((Finset.range 4).filter (fun j => mulA (4 * N + j) = v)).card =
    ((Finset.range 4).filter (fun j => mulB (4 * N + j) = v)).card := by
  simp only [mulA_periodic, mulB_periodic]
  rcases eq_or_ne v 2 with rfl | h2
  · decide
  rcases eq_or_ne v 3 with rfl | h3
  · decide
  have eA : (Finset.range 4).filter (fun j => mulA j = v) = ∅ := by
    refine Finset.filter_false_of_mem fun j _ hj => ?_
    rcases mulA_mem j with h | h <;> rw [h] at hj <;> simp_all
  have eB : (Finset.range 4).filter (fun j => mulB j = v) = ∅ := by
    refine Finset.filter_false_of_mem fun j _ hj => ?_
    rcases mulB_mem j with h | h <;> rw [h] at hj <;> simp_all
  rw [eA, eB]

/-! ## Part 2: The walks -/

/-- The multiplicative walk in `ZMod 5` driven by a multiplier sequence. -/
def walk (m : ℕ → ℕ) : ℕ → ZMod 5
  | 0 => 1
  | n + 1 => walk m n * ((m n : ℕ) : ZMod 5)

/-- Walk `A` reaches the death class `-1 = 4` after two steps. -/
theorem walkA_hits : walk mulA 2 = 4 := by decide

/-- Walk `B` alternates between `1` and `2`. -/
theorem walkB_eq (n : ℕ) : walk mulB n = if n % 2 = 0 then 1 else 2 := by
  induction n with
  | zero => rfl
  | succ n ih =>
    rcases Nat.mod_two_eq_zero_or_one n with hn | hn
    · have h1 : (n + 1) % 2 = 1 := by omega
      rw [walk, ih, mulB, if_pos hn, if_pos hn, h1]
      norm_num
    · have h0 : (n + 1) % 2 = 0 := by omega
      have hn' : ¬ n % 2 = 0 := by omega
      rw [walk, ih, mulB, if_neg hn', if_neg hn', h0]
      decide

/-- **Walk `B` never reaches the death class.** -/
theorem walkB_misses (n : ℕ) : walk mulB n ≠ 4 := by
  rw [walkB_eq]
  split_ifs <;> decide

/-! ## Part 3: Dead End #90 — population statistics do not determine hitting -/

/-- **Dead End #90, witnessed.**  Two multiplier sequences with *identical* empirical
distributions in every window — `B` is a rearrangement of `A` — one of whose walks
reaches the death class `-1 = 4` while the other provably never does.

Population statistics of the multipliers therefore carry no information about whether the
orbit hits `-1`.  Since `walkZ q n = -1 ↔ q ∣ prod n + 1` (`walkZ_eq_neg_one_iff`) and
hitting `-1` cofinally is equivalent to Mullin's conjecture at `q`
(`Mullin.hh_implies_mullin` plus competitor exhaustion), this is precisely the gap that
every population-to-orbit transfer hypothesis — `DeterministicStabilityLemma`,
`PopulationTransfer`, `UCEImpliesCME`, `CRTPointwiseTransferBridge` — has to cross. -/
theorem population_does_not_determine_hitting :
    -- identical multiplier statistics in every window of four steps
    (∀ N v : ℕ,
      ((Finset.range 4).filter (fun j => mulA (4 * N + j) = v)).card =
      ((Finset.range 4).filter (fun j => mulB (4 * N + j) = v)).card) ∧
    -- both sequences are prime-valued at every step
    (∀ k, Nat.Prime (mulA k) ∧ Nat.Prime (mulB k)) ∧
    -- yet one walk reaches the death class …
    walk mulA 2 = 4 ∧
    -- … and the other never does
    (∀ n, walk mulB n ≠ 4) :=
  ⟨block_counts_agree, fun k => ⟨mulA_prime k, mulB_prime k⟩, walkA_hits, walkB_misses⟩

/-! ## Part 4: The order-4 character mod 5 -/

/-- The faithful character of `(ZMod 5)ˣ` with `χ(2) = i`, extended by `0` off the units.
Then `χ(3) = χ(2³) = i³ = -i` and `χ(4) = χ(2²) = -1`. -/
def chi5 (n : ℕ) : ℂ :=
  if n % 5 = 1 then 1
  else if n % 5 = 2 then Complex.I
  else if n % 5 = 3 then -Complex.I
  else if n % 5 = 4 then -1
  else 0

theorem chi5_zero : chi5 0 = 0 := by norm_num [chi5]

theorem chi5_one : chi5 1 = 1 := by norm_num [chi5]

theorem chi5_two : chi5 2 = Complex.I := by norm_num [chi5]

theorem chi5_three : chi5 3 = -Complex.I := by norm_num [chi5]

/-- `chi5` is bounded by `1` in modulus — the side condition carried by
`MultCancelToWalkCancel`. -/
theorem chi5_normSq_le (n : ℕ) : Complex.normSq (chi5 n) ≤ 1 := by
  unfold chi5
  split_ifs <;> simp [Complex.normSq_apply]

/-- `chi5` sums to zero over the residues — the orthogonality side condition. -/
theorem chi5_sum_zero : chi5 0 + chi5 1 + chi5 2 + chi5 3 + chi5 4 = 0 := by
  rw [chi5_zero, chi5_one, chi5_two, chi5_three, show chi5 4 = -1 by norm_num [chi5]]
  ring

/-! ## Part 5: Dead End #117 — bounded multiplier sums, linear walk sums -/

/-- The multiplier character sum for `B` alternates `i, -i`, hence stays bounded. -/
theorem mulB_charSum (K : ℕ) :
    ∑ k ∈ Finset.range K, chi5 (mulB k) = if K % 2 = 0 then 0 else Complex.I := by
  induction K with
  | zero => simp
  | succ K ih =>
    rw [Finset.sum_range_succ, ih, mulB]
    rcases Nat.mod_two_eq_zero_or_one K with hK | hK
    · have h1 : (K + 1) % 2 = 1 := by omega
      rw [if_pos hK, if_pos hK, h1, chi5_two]
      norm_num
    · have h0 : (K + 1) % 2 = 0 := by omega
      have hK' : ¬ K % 2 = 0 := by omega
      rw [if_neg hK', if_neg hK', h0, chi5_three]
      norm_num

/-- The walk positions of `B`, as natural-number representatives. -/
def walkNatB (n : ℕ) : ℕ := if n % 2 = 0 then 1 else 2

theorem walkNatB_spec (n : ℕ) : ((walkNatB n : ℕ) : ZMod 5) = walk mulB n := by
  rw [walkB_eq, walkNatB]
  split_ifs <;> norm_num

/-- The walk character sum for `B` is exactly `M · (1 + i)` after `2M` steps. -/
theorem walkB_charSum (M : ℕ) :
    ∑ n ∈ Finset.range (2 * M), chi5 (walkNatB n) = (M : ℂ) * (1 + Complex.I) := by
  induction M with
  | zero => simp
  | succ M ih =>
    have hrw : 2 * (M + 1) = (2 * M) + 1 + 1 := by ring
    rw [hrw, Finset.sum_range_succ, Finset.sum_range_succ, ih]
    have h0 : walkNatB (2 * M) = 1 := by simp [walkNatB, Nat.mul_mod_right]
    have h1 : walkNatB (2 * M + 1) = 2 := by
      have : (2 * M + 1) % 2 = 1 := by omega
      simp [walkNatB, this]
    rw [h0, h1, chi5_one, chi5_two]
    push_cast
    ring

/-- **Dead End #117, witnessed.**  Multiplier character cancellation does not force walk
character cancellation: for the sequence `B` the multiplier sums are bounded by `1` while
the walk sums grow linearly.

The character carries exactly the side conditions of the repository's own
`MultCancelToWalkCancel` (`normSq ≤ 1`, `χ 0 = 0`, orthogonality), and the multipliers
are primes generating `(ZMod 5)ˣ`, so the counterexample is compatible with the EM
structural properties rather than an artifact of a weak hypothesis. -/
theorem mult_cancel_not_walk_cancel :
    -- the character is legitimate
    (∀ n, Complex.normSq (chi5 n) ≤ 1) ∧
    chi5 0 = 0 ∧
    (chi5 0 + chi5 1 + chi5 2 + chi5 3 + chi5 4 = 0) ∧
    -- the multiplier character sums are bounded, uniformly in `K`
    (∀ K, ‖∑ k ∈ Finset.range K, chi5 (mulB k)‖ ≤ 1) ∧
    -- the walk positions really are the running products …
    (∀ n, ((walkNatB n : ℕ) : ZMod 5) = walk mulB n) ∧
    -- … and their character sums grow linearly
    (∀ M : ℕ, (M : ℝ) ≤ ‖∑ n ∈ Finset.range (2 * M), chi5 (walkNatB n)‖) := by
  refine ⟨chi5_normSq_le, chi5_zero, chi5_sum_zero, fun K => ?_, walkNatB_spec, fun M => ?_⟩
  · rw [mulB_charSum]
    split_ifs <;> simp [Complex.norm_I]
  · rw [walkB_charSum]
    calc (M : ℝ) = |((M : ℂ) * (1 + Complex.I)).re| := by
          simp [Complex.add_re, Complex.mul_re]
      _ ≤ ‖(M : ℂ) * (1 + Complex.I)‖ := Complex.abs_re_le_norm _

/-! ## Part 6: Generation is not coverage -/

/-- The multipliers `{2,3}` generate `(ZMod 5)ˣ`: every nonzero residue is a power of `2`,
and `3 = 2³`.  So `SubgroupEscape` holds for this walk and still does not give coverage —
the multiplicative form of Dead Ends #20 and #130. -/
theorem multipliers_generate :
    ∀ x : ZMod 5, x ≠ 0 → ∃ k : ℕ, k < 4 ∧ (2 : ZMod 5) ^ k = x := by decide

/-! ## Part 7: The integer orbit-barrier thesis -/

/-- **The orbit-specificity barrier, assembled.**  The integer analogue of
`FunctionFieldAnalog.orbit_barrier_thesis`.

Reading the clauses: (1)–(3) are the proved reductions that make an *orbit* statement
sufficient for MC; (4)–(5) are the two proved structural inputs — algebraic generation and
CRT position-blindness — that are everything one gets *for free*; and (6)–(8) are the
witnesses showing that what remains is genuinely not derivable from population data:
statistics do not determine hitting (#90), multiplier cancellation does not force walk
cancellation (#117), and generation does not give coverage (#20/#130).

The gap between (4)–(5) and (6)–(8) is the orbit-specificity barrier, and every open
hypothesis in the reduction network lives in it. -/
theorem integer_orbit_barrier_thesis :
    -- (1) hitting the death class cofinally suffices
    (Mullin.HittingHypothesis → MullinConjecture) ∧
    -- (2) so does the dynamical hitting hypothesis
    (DynamicalHitting → MullinConjecture) ∧
    -- (3) and so does conditional multiplier equidistribution
    (ConditionalMultiplierEquidist → MullinConjecture) ∧
    -- (4) the death class is a divisibility condition on the Euclid number
    (∀ q n : ℕ, walkZ q n = -1 ↔ q ∣ (prod n + 1)) ∧
    -- (5) generation: prime residues escape every proper subgroup (PROVED, free)
    PrimeResidueEscape ∧
    -- (6) #90: identical multiplier statistics, opposite hitting behaviour
    ((∀ N v : ℕ,
        ((Finset.range 4).filter (fun j => mulA (4 * N + j) = v)).card =
        ((Finset.range 4).filter (fun j => mulB (4 * N + j) = v)).card) ∧
      walk mulA 2 = 4 ∧ (∀ n, walk mulB n ≠ 4)) ∧
    -- (7) #117: bounded multiplier sums, linear walk sums
    ((∀ K, ‖∑ k ∈ Finset.range K, chi5 (mulB k)‖ ≤ 1) ∧
      (∀ M : ℕ, (M : ℝ) ≤ ‖∑ n ∈ Finset.range (2 * M), chi5 (walkNatB n)‖)) ∧
    -- (8) #20/#130: generation does not give coverage
    ((∀ x : ZMod 5, x ≠ 0 → ∃ k : ℕ, k < 4 ∧ (2 : ZMod 5) ^ k = x) ∧
      (∀ n : ℕ, _root_.additiveWalk4 n ≠ 2)) := by
  exact ⟨Mullin.hh_implies_mullin, dynamical_hitting_implies_mullin, cme_implies_mc,
    fun _ n => walkZ_eq_neg_one_iff n, prime_residue_escape,
    ⟨block_counts_agree, walkA_hits, walkB_misses⟩,
    ⟨mult_cancel_not_walk_cancel.2.2.2.1, mult_cancel_not_walk_cancel.2.2.2.2.2⟩,
    ⟨multipliers_generate, _root_.alternating_walk_misses_two⟩⟩

/-! ## Part 8: Dead End #179 — two multiplier classes per position is not coverage

The "orbit chain gap" proposal: show that at every cofinally visited walk position at least
*two* distinct multiplier classes appear cofinally, and conclude that the chain expands to
the whole group and reaches `-1`.  The sequence `mulC` below refutes it, in the same group as
`mulA`/`mulB` and with prime multipliers all exceeding `q = 5` (so it is compatible with the
one unconditional constraint at a missing prime, `multipliers_exceed`).  Its residues are
`(2, 4, 2, 3, 4, 3)`, its walk is `1, 2, 3, 1, 3, 2, 1, …`: every visited position is visited
cofinally, with two distinct multiplier classes each time, the residues generate `(ZMod 5)ˣ`,
and the walk never reaches `4`.

The general reason is `death_multiplier_unique`: at a position `x ≠ 0` exactly one multiplier
residue, `-x⁻¹`, is fatal.  So all `q - 2` other classes may be used at every position while
the walk avoids `-1` forever — the avoidance set is a full shift on `q - 2` symbols.  The only
strengthening of the proposal that does work is "the death class `-x⁻¹` appears cofinally at
some cofinal position `x`", which is `DynamicalHitting` restated. -/

/-- Multiplier sequence `C`: period `(7, 19, 7, 13, 19, 13)`, residues `(2, 4, 2, 3, 4, 3)`
mod `5`.  All values are primes greater than `5`. -/
def mulC (k : ℕ) : ℕ :=
  if k % 6 = 0 then 7 else if k % 6 = 1 then 19 else if k % 6 = 2 then 7
  else if k % 6 = 3 then 13 else if k % 6 = 4 then 19 else 13

theorem mulC_periodic (N j : ℕ) : mulC (6 * N + j) = mulC j := by
  have h : (6 * N + j) % 6 = j % 6 := by omega
  simp only [mulC, h]

theorem mulC_mem (k : ℕ) : mulC k = 7 ∨ mulC k = 13 ∨ mulC k = 19 := by
  unfold mulC; split_ifs <;> simp

/-- Every multiplier of `C` is a prime exceeding `q = 5`. -/
theorem mulC_prime_gt (k : ℕ) : Nat.Prime (mulC k) ∧ 5 < mulC k := by
  rcases mulC_mem k with h | h | h <;> rw [h] <;> exact ⟨by norm_num, by norm_num⟩

/-- The walk positions of `C`, as natural-number representatives: period `(1, 2, 3, 1, 3, 2)`. -/
def walkNatC (n : ℕ) : ℕ :=
  if n % 6 = 0 then 1 else if n % 6 = 1 then 2 else if n % 6 = 2 then 3
  else if n % 6 = 3 then 1 else if n % 6 = 4 then 3 else 2

theorem walkC_eq (n : ℕ) : walk mulC n = (walkNatC n : ZMod 5) := by
  induction n with
  | zero => rfl
  | succ n ih =>
    rw [walk, ih]
    have h : n % 6 = 0 ∨ n % 6 = 1 ∨ n % 6 = 2 ∨ n % 6 = 3 ∨ n % 6 = 4 ∨ n % 6 = 5 := by omega
    rcases h with h | h | h | h | h | h
    all_goals
      have h' : (n + 1) % 6 = (n % 6 + 1) % 6 := by omega
      simp only [mulC, walkNatC, h, h']
      decide

theorem walkC_periodic (N j : ℕ) : walk mulC (6 * N + j) = walk mulC j := by
  rw [walkC_eq, walkC_eq]
  have h : (6 * N + j) % 6 = j % 6 := by omega
  simp only [walkNatC, h]

/-- **Walk `C` never reaches the death class.** -/
theorem walkC_misses (n : ℕ) : walk mulC n ≠ 4 := by
  rw [walkC_eq]
  have h : n % 6 = 0 ∨ n % 6 = 1 ∨ n % 6 = 2 ∨ n % 6 = 3 ∨ n % 6 = 4 ∨ n % 6 = 5 := by omega
  rcases h with h | h | h | h | h | h <;> simp only [walkNatC, h] <;> decide

/-- Two offsets `o₁, o₂` of the period that land on the position of step `n` with distinct
multiplier residues give two multiplier classes used cofinally at that position. -/
theorem two_classes_at (n o₁ o₂ : ℕ)
    (h₁ : walk mulC o₁ = walk mulC n) (h₂ : walk mulC o₂ = walk mulC n)
    (hm : ((mulC o₁ : ℕ) : ZMod 5) ≠ ((mulC o₂ : ℕ) : ZMod 5)) :
    ∃ m₁ m₂ : ℕ, ((m₁ : ℕ) : ZMod 5) ≠ ((m₂ : ℕ) : ZMod 5) ∧
      (∀ N, ∃ k, N ≤ k ∧ walk mulC k = walk mulC n ∧ mulC k = m₁) ∧
      (∀ N, ∃ k, N ≤ k ∧ walk mulC k = walk mulC n ∧ mulC k = m₂) :=
  ⟨mulC o₁, mulC o₂, hm,
    fun N => ⟨6 * N + o₁, by omega, (walkC_periodic N o₁).trans h₁, mulC_periodic N o₁⟩,
    fun N => ⟨6 * N + o₂, by omega, (walkC_periodic N o₂).trans h₂, mulC_periodic N o₂⟩⟩

/-- At every step, the position of walk `C` is visited cofinally with two distinct multiplier
classes. -/
theorem walkC_two_classes (n : ℕ) :
    ∃ m₁ m₂ : ℕ, ((m₁ : ℕ) : ZMod 5) ≠ ((m₂ : ℕ) : ZMod 5) ∧
      (∀ N, ∃ k, N ≤ k ∧ walk mulC k = walk mulC n ∧ mulC k = m₁) ∧
      (∀ N, ∃ k, N ≤ k ∧ walk mulC k = walk mulC n ∧ mulC k = m₂) := by
  have hn : walk mulC n = walk mulC (n % 6) := by
    conv_lhs => rw [← Nat.div_add_mod n 6]
    exact walkC_periodic (n / 6) (n % 6)
  have h : n % 6 = 0 ∨ n % 6 = 1 ∨ n % 6 = 2 ∨ n % 6 = 3 ∨ n % 6 = 4 ∨ n % 6 = 5 := by omega
  rcases h with h | h | h | h | h | h <;> rw [h] at hn
  · exact two_classes_at n 0 3 (by rw [hn]) (by rw [hn]; decide) (by decide)
  · exact two_classes_at n 1 5 (by rw [hn]) (by rw [hn]; decide) (by decide)
  · exact two_classes_at n 2 4 (by rw [hn]) (by rw [hn]; decide) (by decide)
  · exact two_classes_at n 3 0 (by rw [hn]) (by rw [hn]; decide) (by decide)
  · exact two_classes_at n 4 2 (by rw [hn]) (by rw [hn]; decide) (by decide)
  · exact two_classes_at n 5 1 (by rw [hn]) (by rw [hn]; decide) (by decide)

/-- At a position `x ≠ 0` of `ZMod q`, `q` prime, exactly one multiplier residue is fatal:
`x * m = -1` iff `m = -x⁻¹`.  Every other class keeps the walk alive, so the avoidance set is
a full shift on `q - 2` symbols and no "many classes per position" hypothesis short of naming
the death class can force a hit. -/
theorem death_multiplier_unique {q : ℕ} [Fact q.Prime] (x m : ZMod q) (hx : x ≠ 0) :
    x * m = -1 ↔ m = -x⁻¹ := by
  have h := mul_right_inj' hx (b := m) (c := -x⁻¹)
  rw [mul_neg, mul_inv_cancel₀ hx] at h
  exact h

/-- **Dead End #179, witnessed.**  Two distinct multiplier classes at every cofinally visited
position, generating multiplier residues, prime multipliers all above `q` — and the walk still
never reaches the death class.  The "orbit chain gap" cannot be closed by counting classes per
position; only the death class itself counts, and asking for it is `DynamicalHitting`. -/
theorem two_classes_not_coverage :
    -- prime multipliers, all exceeding q = 5
    (∀ k, Nat.Prime (mulC k) ∧ 5 < mulC k) ∧
    -- whose residues generate (ZMod 5)ˣ: the first multiplier is 7 ≡ 2, a generator
    ((mulC 0 : ℕ) : ZMod 5) = 2 ∧
    (∀ x : ZMod 5, x ≠ 0 → ∃ k : ℕ, k < 4 ∧ (2 : ZMod 5) ^ k = x) ∧
    -- at every visited position two distinct multiplier classes are used cofinally
    (∀ n, ∃ m₁ m₂ : ℕ, ((m₁ : ℕ) : ZMod 5) ≠ ((m₂ : ℕ) : ZMod 5) ∧
      (∀ N, ∃ k, N ≤ k ∧ walk mulC k = walk mulC n ∧ mulC k = m₁) ∧
      (∀ N, ∃ k, N ≤ k ∧ walk mulC k = walk mulC n ∧ mulC k = m₂)) ∧
    -- yet the walk never reaches the death class
    (∀ n, walk mulC n ≠ 4) :=
  ⟨mulC_prime_gt, by decide, multipliers_generate, walkC_two_classes, walkC_misses⟩

end OrbitBarrier

end
