/-
Copyright (c) 2025 Mullin's Conjecture Project. All rights reserved.
Released under Apache 2.0 license.
-/
import Mathlib.Data.Nat.PrimeFin
import Mathlib.Data.Nat.Factorization.Basic
import Mathlib.Data.ZMod.Basic
import Mathlib.Tactic.NormNum.Prime
import Mathlib.Tactic.Ring
import Mathlib.Tactic.IntervalCases

/-!
# The Second Euclid–Mullin Sequence and the Cox–van der Poorten Obstruction

The **second Euclid–Mullin sequence** (OEIS A000946) replaces the *smallest*
prime factor by the *largest* one:

    Q 0 = 2,    r n = maxFac (Q n + 1),    Q (n+1) = Q n * r n

so the sequence of multipliers begins `2, 3, 7, 43, 139, 50207, ...`.

Unlike the first (minFac) sequence, where Mullin's Conjecture is open, this
sequence **provably omits primes**. The classical argument, due to Cox and van
der Poorten, shows that certain small primes can never occur. This file
machine-verifies the argument for the prime `5`:

  **`five_not_mem_mseq : ∀ n, mseq n ≠ 5`**

an unconditional, computation-free missing-prime theorem.

## The argument (three moves)

1. *Congruence bookkeeping* (`mprod_mod_four`, `three_not_dvd_mprod_succ`):
   for `n ≥ 1` the accumulator satisfies `Q n ≡ 2 (mod 4)` and `3 ∣ Q n`,
   hence the Euclid number `N = Q n + 1` satisfies `N ≡ 3 (mod 4)` and
   `3 ∤ N`.

2. *Smoothness forcing* (`eq_pow_five_of_maxFac_five`): if
   `maxFac N = 5` then **every** prime factor of `N` is `≤ 5`; oddness kills
   `2` and step 1 kills `3`, so `N = 5 ^ c`.

3. *The mod-4 collision* (`maxFac_ne_five_of_mod_four`): `5 ^ c ≡ 1 (mod 4)`
   for every `c`, contradicting `N ≡ 3 (mod 4)`.

## Why this is selection-rule ASYMMETRIC (the scientific content)

Move 2 is the *only* place the selection rule enters, and it is exactly where
the minFac world differs:

* Under **maxFac**, the hypothesis `maxFac N = 5` is a **thin multiplicative
  condition**: it says `N` is `5`-smooth, i.e. `N` lies in the multiplicative
  semigroup generated by `{2, 3, 5}`. Intersecting with the congruence data
  (`N` odd, `3 ∤ N`) collapses that semigroup to the single geometric
  progression `{5 ^ c}`, whose members all lie in the single residue class
  `1 (mod 4)`. A congruence obstruction then has something to bite on.

* Under **minFac**, the hypothesis `minFac N = 5` is an **open congruence
  condition**: it says only that `2 ∤ N` and `3 ∤ N`, i.e. `N` lies in a
  *union of residue classes* mod 6 — a positive-density set that meets every
  residue class mod 4 (and mod anything coprime to 6). It places **no**
  restriction whatsoever on the large prime factors of `N`. So `N` is free to
  be `≡ 3 (mod 4)`, and the mod-4 collision has nothing to bite on.

This contrast is witnessed formally, on a single number, by
`min_side_no_smoothness_forcing` together with `maxFac_thirtyfive_ne_five`:
the number `N = 35` is odd, coprime to `3`, and `≡ 3 (mod 4)`; it satisfies
`Nat.minFac 35 = 5` yet is **not** a power of `5`, whereas `maxFac 35 ≠ 5`.
The same `N` is a "forcing state for 5" on the min side and is blocked on the
max side. Hence the Cox–van der Poorten obstruction class is *inhabited* for
the max rule and gives no information for the min rule.

## Attribution / literature check

The result "5 never occurs in the second Euclid–Mullin sequence" is classically
attributed to

* C. D. Cox and A. J. van der Poorten, *On a sequence of prime numbers*,
  J. Austral. Math. Soc. **8** (1968), 571–574,

who showed that a number of small primes (5, 11, 13, 17, 19, 23, ...) are
omitted. **This attribution has not been independently verified inside the
present (offline) environment**: no network access was available, so the
statement of the 1968 paper could not be consulted directly. What *is*
verified here is the mathematics: the reconstruction below is complete and
machine-checked, and it proves the omission of `5`.

A remark on the reach of *this* reconstruction: the mod-4 collision closes the
case `q = 5` and *only* `q = 5` among the primes not already in the sequence.
For `q = 11` the forced smooth numbers are `5^a 7^b 11^c` and for `q = 13` they
are `5^a 7^b 11^c 13^d`; since `7 ≡ 11 ≡ 3 (mod 4)`, these products can and do
hit the class `3 (mod 4)`, so mod 4 alone gives no contradiction. Those cases
require additional congruence or quadratic-residue input beyond what is
formalized here, and no claim about them is made in this file.

## Contents

* `maxFac` and its basic API (`maxFac_mem`, `maxFac_dvd`, `maxFac_prime`,
  `le_maxFac`, `maxFac_eq_self_of_prime`).
* The second sequence `mseq` / `mprod`, with primality, the coprimality
  cascade (`mseq_injective`), oddness, and the mod-4 / mod-12 structure.
* The smoothness-forcing and mod-4 collision lemmas.
* `five_not_mem_mseq` — the headline theorem.
* The max-side transition system `MaxR`, `MaxPropagating`, `MaxForcingState`,
  `MaxBlocks`, and the obstruction package `MaxCvdPObstruction`, together with
  the explicit instance `max_cvdp_obstruction_five` at modulus `12`.
-/

namespace MaxVariant

open Nat

/-! ## Part 1: the largest prime factor -/

/-- The **largest prime factor** of `n`, defined as the supremum of the finite
set `n.primeFactors` (so `maxFac 0 = maxFac 1 = 0`). -/
def maxFac (n : ℕ) : ℕ := n.primeFactors.sup id

/-- For `n > 1`, `maxFac n` is an actual prime factor of `n`. -/
theorem maxFac_mem {n : ℕ} (h : 1 < n) : maxFac n ∈ n.primeFactors := by
  have hne : n.primeFactors.Nonempty := Nat.nonempty_primeFactors.mpr h
  have hsup : n.primeFactors.sup id = n.primeFactors.max' hne := by
    rw [Finset.max'_eq_sup', Finset.sup'_eq_sup]
  rw [maxFac, hsup]
  exact n.primeFactors.max'_mem hne

/-- `maxFac n` is prime when `n > 1`. -/
theorem maxFac_prime {n : ℕ} (h : 1 < n) : (maxFac n).Prime :=
  Nat.prime_of_mem_primeFactors (maxFac_mem h)

/-- `maxFac n` divides `n` when `n > 1`. -/
theorem maxFac_dvd {n : ℕ} (h : 1 < n) : maxFac n ∣ n :=
  Nat.dvd_of_mem_primeFactors (maxFac_mem h)

/-- Every prime factor of `n` is at most `maxFac n`. -/
theorem le_maxFac {n p : ℕ} (hp : p ∈ n.primeFactors) : p ≤ maxFac n :=
  Finset.le_sup (f := id) hp

/-- The largest prime factor of a prime is itself. -/
theorem maxFac_eq_self_of_prime {p : ℕ} (hp : p.Prime) : maxFac p = p := by
  rw [maxFac, hp.primeFactors, Finset.sup_singleton]
  rfl

/-! ## Part 2: the second Euclid–Mullin sequence -/

/-- Auxiliary recursion returning `(r n, Q n)`: the `n`-th multiplier together
with the accumulated product. -/
def maxAux : ℕ → ℕ × ℕ
  | 0 => (2, 2)
  | n + 1 =>
    let Q := (maxAux n).2
    let r := maxFac (Q + 1)
    (r, Q * r)

/-- The `n`-th term of the second Euclid–Mullin sequence: `2, 3, 7, 43, ...` -/
def mseq (n : ℕ) : ℕ := (maxAux n).1

/-- The accumulated product `Q n = mseq 0 * ... * mseq n`. -/
def mprod (n : ℕ) : ℕ := (maxAux n).2

theorem mseq_zero : mseq 0 = 2 := rfl

theorem mprod_zero : mprod 0 = 2 := rfl

theorem mprod_succ (n : ℕ) : mprod (n + 1) = mprod n * mseq (n + 1) := rfl

theorem mseq_succ (n : ℕ) : mseq (n + 1) = maxFac (mprod n + 1) := rfl

/-! ### Structural properties -/

/-- The accumulator is always at least `2`. -/
theorem mprod_ge_two (n : ℕ) : 2 ≤ mprod n := by
  induction n with
  | zero => exact le_of_eq mprod_zero.symm
  | succ n ih =>
    have hgt : 1 < mprod n + 1 := by omega
    have hp : (maxFac (mprod n + 1)).Prime := maxFac_prime hgt
    have h2 : 2 ≤ mseq (n + 1) := by rw [mseq_succ]; exact hp.two_le
    calc 2 ≤ mprod n := ih
      _ ≤ mprod n * mseq (n + 1) := Nat.le_mul_of_pos_right _ (by omega)
      _ = mprod (n + 1) := (mprod_succ n).symm

/-- Every term of the second sequence is prime. -/
theorem mseq_prime : ∀ n, (mseq n).Prime := by
  intro n
  cases n with
  | zero => rw [mseq_zero]; exact Nat.prime_two
  | succ k =>
    rw [mseq_succ]
    exact maxFac_prime (by have := mprod_ge_two k; omega)

/-- Each term divides the Euclid number it was extracted from. -/
theorem mseq_succ_dvd (n : ℕ) : mseq (n + 1) ∣ mprod n + 1 := by
  rw [mseq_succ]
  exact maxFac_dvd (by have := mprod_ge_two n; omega)

theorem mseq_dvd_mprod_self : ∀ n, mseq n ∣ mprod n := by
  intro n
  cases n with
  | zero => rw [mseq_zero, mprod_zero]
  | succ k => rw [mprod_succ]; exact Dvd.intro_left _ rfl

theorem mprod_dvd_mprod {m n : ℕ} (h : m ≤ n) : mprod m ∣ mprod n := by
  induction n with
  | zero => rw [Nat.le_zero.mp h]
  | succ k ih =>
    rcases Nat.lt_or_ge m (k + 1) with hlt | hge
    · exact dvd_trans (ih (by omega)) ⟨mseq (k + 1), mprod_succ k⟩
    · rw [Nat.le_antisymm h hge]

/-- Each term divides every later accumulator. -/
theorem mseq_dvd_mprod {m n : ℕ} (h : m ≤ n) : mseq m ∣ mprod n :=
  dvd_trans (mseq_dvd_mprod_self m) (mprod_dvd_mprod h)

/-- **Coprimality cascade**: distinct indices give distinct primes. -/
theorem mseq_ne_of_lt {m n : ℕ} (hlt : m < n) : mseq m ≠ mseq n := by
  intro heq
  obtain ⟨k, rfl⟩ : ∃ k, n = k + 1 := ⟨n - 1, by omega⟩
  have hdvd1 : mseq m ∣ mprod k := mseq_dvd_mprod (by omega)
  have hdvd2 : mseq m ∣ mprod k + 1 := heq ▸ mseq_succ_dvd k
  have hone : mseq m ∣ 1 := (Nat.dvd_add_right hdvd1).mp hdvd2
  have h2 : 2 ≤ mseq m := (mseq_prime m).two_le
  have h1 : mseq m ≤ 1 := Nat.le_of_dvd one_pos hone
  omega

/-- No prime occurs twice in the second sequence. -/
theorem mseq_injective : Function.Injective mseq := by
  intro m n h
  rcases Nat.lt_trichotomy m n with hlt | heq | hgt
  · exact absurd h (mseq_ne_of_lt hlt)
  · exact heq
  · exact absurd h.symm (mseq_ne_of_lt hgt)

/-! ### Parity and the mod-4 structure -/

theorem two_dvd_mprod (n : ℕ) : 2 ∣ mprod n := by
  have := mseq_dvd_mprod (m := 0) (n := n) (Nat.zero_le n)
  rwa [mseq_zero] at this

/-- Euclid numbers of the second sequence are odd. -/
theorem mprod_succ_odd (n : ℕ) : (mprod n + 1) % 2 = 1 := by
  obtain ⟨a, ha⟩ := two_dvd_mprod n
  omega

/-- Every multiplier from step 1 on is odd. -/
theorem mseq_succ_odd (n : ℕ) : mseq (n + 1) % 2 = 1 := by
  rcases Nat.even_or_odd (mseq (n + 1)) with he | ho
  · exfalso
    have h2 : (2 : ℕ) ∣ mprod n + 1 := dvd_trans he.two_dvd (mseq_succ_dvd n)
    obtain ⟨b, hb⟩ := h2
    have := mprod_succ_odd n
    omega
  · exact Nat.odd_iff.mp ho

/-- The prime `3` occurs at step 1. -/
theorem mseq_one : mseq 1 = 3 := by
  rw [mseq_succ, mprod_zero]
  exact maxFac_eq_self_of_prime (by norm_num)

theorem mprod_one : mprod 1 = 6 := by
  rw [mprod_succ, mprod_zero, mseq_one]

/-- `Q n ≡ 2 (mod 4)` for `n ≥ 1`. -/
theorem mprod_mod_four : ∀ {n : ℕ}, 1 ≤ n → mprod n % 4 = 2 := by
  intro n
  induction n with
  | zero => omega
  | succ k ih =>
    intro _
    rcases Nat.eq_zero_or_pos k with rfl | hk
    · have h6 : mprod (0 + 1) = 6 := mprod_one
      omega
    · have hQ : mprod k % 4 = 2 := ih hk
      have hr : mseq (k + 1) % 2 = 1 := mseq_succ_odd k
      obtain ⟨c, hc⟩ : ∃ c, mprod k * mseq (k + 1) = 4 * c + 2 := by
        refine ⟨2 * (mprod k / 4) * (mseq (k + 1) / 2) + (mprod k / 4)
                  + (mseq (k + 1) / 2), ?_⟩
        have h1 : mprod k = 4 * (mprod k / 4) + 2 := by omega
        have h2 : mseq (k + 1) = 2 * (mseq (k + 1) / 2) + 1 := by omega
        calc mprod k * mseq (k + 1)
            = (4 * (mprod k / 4) + 2) * (2 * (mseq (k + 1) / 2) + 1) := by
              rw [← h1, ← h2]
          _ = 4 * (2 * (mprod k / 4) * (mseq (k + 1) / 2) + (mprod k / 4)
                  + (mseq (k + 1) / 2)) + 2 := by ring
      rw [mprod_succ, hc]
      omega

/-- `3 ∣ Q n` for `n ≥ 1`. -/
theorem three_dvd_mprod {n : ℕ} (hn : 1 ≤ n) : 3 ∣ mprod n := by
  have := mseq_dvd_mprod (m := 1) (n := n) hn
  rwa [mseq_one] at this

/-- Hence `3` never divides a later Euclid number. -/
theorem three_not_dvd_mprod_succ {n : ℕ} (hn : 1 ≤ n) : ¬ (3 ∣ mprod n + 1) := by
  intro h
  obtain ⟨a, ha⟩ := three_dvd_mprod hn
  obtain ⟨b, hb⟩ := h
  omega

/-- The combined congruence: `Q n ≡ 6 (mod 12)` for `n ≥ 1`. -/
theorem mprod_mod_twelve {n : ℕ} (hn : 1 ≤ n) : mprod n % 12 = 6 := by
  have h4 := mprod_mod_four hn
  obtain ⟨a, ha⟩ := three_dvd_mprod hn
  omega

/-! ## Part 3: smoothness forcing and the mod-4 collision -/

/-- **Smoothness forcing (B2).** If the largest prime factor of an odd number
`N ≥ 3` coprime to `3` is `5`, then `N` is a power of `5`.

This is where the *max* selection rule does the work: `maxFac N = 5` bounds
*all* prime factors of `N`, a thin multiplicative condition. -/
theorem eq_pow_five_of_maxFac_five {N : ℕ} (hN : 3 ≤ N) (hodd : N % 2 = 1)
    (h3 : ¬ (3 ∣ N)) (h5 : maxFac N = 5) : ∃ c, N = 5 ^ c := by
  refine ⟨N.primeFactorsList.length, Nat.eq_prime_pow_of_unique_prime_dvd (by omega) ?_⟩
  intro d hd hdvd
  have hmem : d ∈ N.primeFactors := Nat.mem_primeFactors.mpr ⟨hd, hdvd, by omega⟩
  have hle : d ≤ 5 := h5 ▸ le_maxFac hmem
  have hne2 : d ≠ 2 := by
    rintro rfl
    obtain ⟨k, hk⟩ := hdvd
    omega
  have hne3 : d ≠ 3 := by
    rintro rfl
    exact h3 hdvd
  have hge : 2 ≤ d := hd.two_le
  interval_cases d
  · exact absurd rfl hne2
  · exact absurd rfl hne3
  · exact absurd hd (by norm_num)
  · rfl

/-- Powers of `5` are `1` mod `4`. -/
theorem five_pow_mod_four (c : ℕ) : 5 ^ c % 4 = 1 := by
  rw [Nat.pow_mod]
  norm_num

/-- **The mod-4 collision (B3).** An odd `N ≥ 3` coprime to `3` with
`N ≡ 3 (mod 4)` cannot have largest prime factor `5`. -/
theorem maxFac_ne_five_of_mod_four {N : ℕ} (hN : 3 ≤ N) (hodd : N % 2 = 1)
    (h3 : ¬ (3 ∣ N)) (h4 : N % 4 = 3) : maxFac N ≠ 5 := by
  intro h5
  obtain ⟨c, rfl⟩ := eq_pow_five_of_maxFac_five hN hodd h3 h5
  have := five_pow_mod_four c
  omega

/-- **Cox–van der Poorten (headline theorem).** The prime `5` never occurs in
the second Euclid–Mullin sequence. -/
theorem five_not_mem_mseq (n : ℕ) : mseq n ≠ 5 := by
  match n with
  | 0 => rw [mseq_zero]; norm_num
  | 1 => rw [mseq_one]; norm_num
  | (k + 2) =>
    rw [mseq_succ]
    have hk : 1 ≤ k + 1 := by omega
    have hQ4 : mprod (k + 1) % 4 = 2 := mprod_mod_four hk
    refine maxFac_ne_five_of_mod_four ?_ (mprod_succ_odd (k + 1))
      (three_not_dvd_mprod_succ hk) (by omega)
    have := mprod_ge_two (k + 1)
    omega

/-- Restated: `5` is a missing prime for the max-rule sequence. -/
theorem five_missing : ¬ ∃ n, mseq n = 5 := by
  rintro ⟨n, hn⟩
  exact five_not_mem_mseq n hn

/-! ## Part 4: the obstruction, packaged

The max-side transition system. A state is a residue `r` of the accumulator
mod `m`; a transition consumes an odd Euclid number `N ≥ 3` congruent to
`r + 1` and multiplies `r` by the residue of `maxFac N`.

**Coordination note.** Task A (`EM/Obstruction/NoInvariant.lean`) owns the
canonical `CvdPObstruction` / `Propagating` / `ForcingState` definitions for
the *min* rule. The definitions below are the max-side mirror images, kept
local and prefixed `Max` so that the two files can be developed independently.
See the reconciliation section at the end of this file. -/

/-- One step of the max-side transition system at modulus `m`. -/
def MaxR (m : ℕ) (r r' : ZMod m) : Prop :=
  ∃ N : ℕ, Odd N ∧ 3 ≤ N ∧ (N : ZMod m) = r + 1 ∧ r' = r * (maxFac N : ZMod m)

/-- A set of states is *propagating* if it is closed under the transition. -/
def MaxPropagating (m : ℕ) (S : Set (ZMod m)) : Prop :=
  ∀ r ∈ S, ∀ r', MaxR m r r' → r' ∈ S

/-- `r` is a *forcing state* for the prime `q` if some legal Euclid number at
`r` has largest prime factor `q`. -/
def MaxForcingState (m q : ℕ) (r : ZMod m) : Prop :=
  ∃ N : ℕ, Odd N ∧ 3 ≤ N ∧ (N : ZMod m) = r + 1 ∧ maxFac N = q

/-- `S` *blocks* `q` if it contains no forcing state for `q`. -/
def MaxBlocks (m q : ℕ) (S : Set (ZMod m)) : Prop :=
  ∀ r ∈ S, ¬ MaxForcingState m q r

/-- A **Cox–van der Poorten obstruction** to the prime `q` at modulus `m`:
a propagating set of residues that blocks `q` and contains the orbit tail of
the actual max-rule sequence. -/
structure MaxCvdPObstruction (q m : ℕ) (S : Set (ZMod m)) : Prop where
  propagating : MaxPropagating m S
  blocks : MaxBlocks m q S
  contains_tail : ∀ n, 1 ≤ n → ((mprod n : ℕ) : ZMod m) ∈ S

/-! ### Casting helpers at modulus 12 -/

private theorem zmod_twelve_of_cast {N : ℕ} (h : (N : ZMod 12) = 7) : N % 12 = 7 := by
  have h' : (N : ZMod 12) = ((7 : ℕ) : ZMod 12) := by push_cast; exact h
  have := (ZMod.natCast_eq_natCast_iff' N 7 12).mp h'
  simpa using this

private theorem cast_of_mod_twelve {N : ℕ} (h : N % 12 = 6) : (N : ZMod 12) = 6 := by
  have h' : N % 12 = 6 % 12 := by omega
  have := (ZMod.natCast_eq_natCast_iff' N 6 12).mpr h'
  push_cast at this
  exact this

private theorem zmod12_six_mul_odd {p : ℕ} (hp : p % 2 = 1) :
    (6 : ZMod 12) * (p : ZMod 12) = 6 := by
  have h : (6 * p) % 12 = 6 % 12 := by omega
  have := (ZMod.natCast_eq_natCast_iff' (6 * p) 6 12).mpr h
  push_cast at this
  exact this

/-! ### The explicit obstruction: `S = {6} ⊆ ZMod 12` blocks `5` -/

/-- The singleton `{6} ⊆ ZMod 12` is propagating: an odd Euclid number
`N ≡ 7 (mod 12)` has odd largest prime factor `p`, and `6 * p ≡ 6 (mod 12)`. -/
theorem maxPropagating_six : MaxPropagating 12 {(6 : ZMod 12)} := by
  rintro r hr r' ⟨N, -, hN3, hcast, hr'⟩
  have hr6 : r = 6 := hr
  subst hr6
  have hN7 : (N : ZMod 12) = 7 := by rw [hcast]; norm_num
  have hmod : N % 12 = 7 := zmod_twelve_of_cast hN7
  have hp : maxFac N ∣ N := maxFac_dvd (by omega)
  have hpodd : maxFac N % 2 = 1 := by
    rcases Nat.even_or_odd (maxFac N) with he | ho
    · exfalso
      obtain ⟨b, hb⟩ := dvd_trans he.two_dvd hp
      omega
    · exact Nat.odd_iff.mp ho
  show r' ∈ ({(6 : ZMod 12)} : Set (ZMod 12))
  rw [hr']
  exact zmod12_six_mul_odd hpodd

/-- The singleton `{6} ⊆ ZMod 12` blocks the prime `5`: this is exactly the
smoothness forcing plus the mod-4 collision. -/
theorem maxBlocks_six_five : MaxBlocks 12 5 {(6 : ZMod 12)} := by
  rintro r hr ⟨N, -, hN3, hcast, h5⟩
  have hr6 : r = 6 := hr
  subst hr6
  have hN7 : (N : ZMod 12) = 7 := by rw [hcast]; norm_num
  have hmod : N % 12 = 7 := zmod_twelve_of_cast hN7
  have h3 : ¬ (3 ∣ N) := by
    intro hdvd
    obtain ⟨a, ha⟩ := hdvd
    omega
  exact maxFac_ne_five_of_mod_four hN3 (by omega) h3 (by omega) h5

/-- The real orbit tail lies in `{6}`. -/
theorem mprod_mem_six {n : ℕ} (hn : 1 ≤ n) : ((mprod n : ℕ) : ZMod 12) ∈ ({(6 : ZMod 12)} : Set (ZMod 12)) :=
  cast_of_mod_twelve (mprod_mod_twelve hn)

/-- **B4: the obstruction, packaged.** `{6} ⊆ ZMod 12` is a Cox–van der Poorten
obstruction to the prime `5` for the max-rule sequence. -/
theorem max_cvdp_obstruction_five : MaxCvdPObstruction 5 12 {(6 : ZMod 12)} where
  propagating := maxPropagating_six
  blocks := maxBlocks_six_five
  contains_tail := fun _ hn => mprod_mem_six hn

/-- The actual sequence step is an instance of the abstract transition, so the
obstruction really does apply to it. -/
theorem mprod_step_maxR (n : ℕ) :
    MaxR 12 ((mprod n : ℕ) : ZMod 12) ((mprod (n + 1) : ℕ) : ZMod 12) := by
  refine ⟨mprod n + 1, Nat.odd_iff.mpr (mprod_succ_odd n),by have := mprod_ge_two n; omega, by push_cast; ring, ?_⟩
  rw [mprod_succ, mseq_succ]
  push_cast
  ring

/-- Abstract re-derivation of the headline theorem from the packaged
obstruction: any prime blocked by a propagating set containing the orbit tail
is missing from the sequence (from step 2 on). -/
theorem missing_of_obstruction {q m : ℕ} {S : Set (ZMod m)}
    (h : MaxCvdPObstruction q m S) {n : ℕ} (hn : 1 ≤ n) : mseq (n + 1) ≠ q := by
  intro hq
  refine h.blocks _ (h.contains_tail n hn) ⟨mprod n + 1, Nat.odd_iff.mpr (mprod_succ_odd n),?_, by push_cast; ring, ?_⟩
  · have := mprod_ge_two n; omega
  · rw [← mseq_succ]; exact hq

/-- `five_not_mem_mseq` re-obtained through the obstruction package. -/
theorem five_not_mem_mseq' {n : ℕ} (hn : 1 ≤ n) : mseq (n + 1) ≠ 5 :=
  missing_of_obstruction max_cvdp_obstruction_five hn

/-! ## Part 5: the min/max asymmetry, witnessed -/

/-- **The asymmetry witness.** Under the *min* rule, `minFac N = 5` does not
force `5`-smoothness: `N = 35` is odd, coprime to `3`, congruent to `3` mod `4`
— i.e. it satisfies every congruence hypothesis used in the max-side argument —
has `minFac 35 = 5`, and yet is not a power of `5`. The mod-4 collision
therefore has nothing to bite on in the min world. -/
theorem min_side_no_smoothness_forcing :
    ∃ N : ℕ, 3 ≤ N ∧ N % 2 = 1 ∧ ¬ (3 ∣ N) ∧ N % 4 = 3 ∧
      Nat.minFac N = 5 ∧ ¬ ∃ c, N = 5 ^ c := by
  refine ⟨35, by norm_num, by norm_num, by decide, by norm_num, by norm_num, ?_⟩
  rintro ⟨c, hc⟩
  have h7 : (7 : ℕ) ∣ 5 ^ c := hc ▸ (by norm_num : (7 : ℕ) ∣ 35)
  have := (Nat.Prime.dvd_of_dvd_pow (by norm_num : Nat.Prime 7)) h7
  norm_num at this

/-- The same number is *blocked* on the max side: `maxFac 35 ≠ 5`. Note this is
proved abstractly from `maxFac_ne_five_of_mod_four`, not by factoring `35`. -/
theorem maxFac_thirtyfive_ne_five : maxFac 35 ≠ 5 :=
  maxFac_ne_five_of_mod_four (by norm_num) (by norm_num) (by decide) (by norm_num)

/-- The asymmetry, as a single statement: there is a number satisfying all the
congruence side conditions of the Cox–van der Poorten argument which is a
forcing state for `5` under `minFac` but not under `maxFac`. -/
theorem cvdp_selection_rule_asymmetry :
    ∃ N : ℕ, 3 ≤ N ∧ N % 2 = 1 ∧ ¬ (3 ∣ N) ∧ N % 4 = 3 ∧
      Nat.minFac N = 5 ∧ maxFac N ≠ 5 :=
  ⟨35, by norm_num, by norm_num, by decide, by norm_num, by norm_num,
    maxFac_thirtyfive_ne_five⟩

/-! ## Landscape -/

/-- Summary of what this file establishes. -/
theorem max_variant_landscape :
    (∀ n, (mseq n).Prime) ∧
    Function.Injective mseq ∧
    (∀ n, 1 ≤ n → mprod n % 4 = 2) ∧
    (∀ n, mseq n ≠ 5) ∧
    MaxCvdPObstruction 5 12 {(6 : ZMod 12)} ∧
    (∃ N : ℕ, Nat.minFac N = 5 ∧ maxFac N ≠ 5 ∧ N % 4 = 3) :=
  ⟨mseq_prime, mseq_injective, fun _ hn => mprod_mod_four hn, five_not_mem_mseq,
    max_cvdp_obstruction_five,
    ⟨35, by norm_num, maxFac_thirtyfive_ne_five, by norm_num⟩⟩

/-! ## Reconciliation — DISCHARGED (Session 307)

Carried out in `EM/Obstruction/RuleTransition.lean`.  The rule-parameterised system is
`RuleTransition.R Φ m`, and `MaxR` / `MaxForcingState` are the case `Φ = maxFac`
(`maxR_iff`, `maxForcingState_iff`, both `Iff.rfl`); `CvdP.Transition` is the case
`Φ = Nat.minFac` (`minR_iff`).  This file's `max_cvdp_obstruction_five` supplies the
inhabitant, `RuleTransition.no_min_rule_obstruction` the complementary emptiness at every
modulus, and `RuleTransition.cvdp_dichotomy` states them together.  The asymmetry theorems
below are retained as the concrete illustration.

Original note follows.

### Original TODO

At merge time the definitions `MaxR`, `MaxPropagating`, `MaxForcingState`,
`MaxBlocks`, `MaxCvdPObstruction` in this file should be unified with the
canonical min-side definitions in `EM/Obstruction/NoInvariant.lean` (Task A).
The intended common shape is a transition system parameterised by a
*selection rule* `Φ : ℕ → ℕ` (`Nat.minFac` on the min side, `maxFac` here):

    R_Φ,m r r'  :=  ∃ N, Odd N ∧ 3 ≤ N ∧ (N : ZMod m) = r + 1 ∧ r' = r * Φ N

with `Propagating`, `ForcingState`, `Blocks`, `CvdPObstruction` defined
verbatim from `R_Φ,m`. This file then supplies the statement
"the obstruction class for `Φ = maxFac` is **inhabited**"
(`max_cvdp_obstruction_five`), and Task A supplies the complementary statement
for `Φ = Nat.minFac`. The asymmetry theorems
(`min_side_no_smoothness_forcing`, `cvdp_selection_rule_asymmetry`) are already
stated in rule-neutral terms and should survive the merge unchanged. -/

end MaxVariant
