#!/usr/bin/env python3
r"""Generate the dead-ends catalogue from tools/dead_ends.tsv.

Outputs:
  paper/dead_ends_table.tex   — the complete numbered catalogue (longtable), grouped by category
  docs/dead_ends_catalog.md   — the same catalogue as markdown (local docs mirror)
and prints the counts (entries, witnessed, revival ≥ 2, unassigned numbers) so that
`deadEndCount` / `witnessedDeadEndCount` / `revivableDeadEndCount` in EM/Meta/DeadEnds.lean
can be checked against the TSV.  Run from the repo root:  python3 tools/gen_dead_ends.py

TSV columns (tab-separated, `#` lines are comments):
  num  cat  name  approach  rationale  session  witness  revival  status
`cat` ∈ {OS,TM,SM,CI,SF,CO,DG,AG,MR,--}; `--` marks a number that was never assigned (row kept so
that the numbering is accounted for).  `witness` is a Lean theorem name (or `—`); `revival` is
0–3 (or `-`).  Text fields are LaTeX (math in $…$, `\#`), and are converted lightly for markdown.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TSV = ROOT / "tools" / "dead_ends.tsv"

CATS = [
    ("OS", "Orbit specificity", "population or ensemble statistics do not determine what one orbit does"),
    ("DG", "Decorrelation gap", "multiplier-level cancellation or independence does not transfer to the walk"),
    ("AG", "Aggregate gap", "an average-case or aggregate bound does not give the per-fibre or per-class bound needed"),
    ("CO", "Collapse", "the proposed hypothesis is definitionally (or by a short argument) equivalent to an existing one, usually CME, CCSB or MC itself"),
    ("CI", "Circularity", "the argument presupposes the conclusion or an equivalent"),
    ("SF", "Structurally false", "the proposed statement is false: an explicit counterexample or a proved refutation"),
    ("TM", "Technique mismatch", "the tool needs structure (independence, multiplicativity, stationarity, algebraic families) that the walk provably lacks"),
    ("SM", "Scale mismatch", "the error term of the tool exceeds the signal on an $O(\\log x)$-term or exponentially sparse orbit"),
    ("MR", "Methodological rules", "not mathematical obstructions but standing rules of the project (no numerical certificates, no instance-by-instance work), numbered in the earliest sessions"),
    ("--", "Unassigned numbers", "numbers that were never assigned to an entry in any session log (kept so the numbering is accounted for)"),
]


def tex_escape_plain(s: str) -> str:
    return s


def md_from_tex(s: str) -> str:
    s = s.replace("\\#", "#").replace("\\_", "_").replace("\\&", "&").replace("\\%", "%")
    s = re.sub(r"\\code\{([^}]*)\}", r"`\1`", s)
    s = re.sub(r"\\emph\{([^}]*)\}", r"*\1*", s)
    s = re.sub(r"\\textbf\{([^}]*)\}", r"**\1**", s)
    s = s.replace("~", " ").replace("\\,", " ").replace("---", "—").replace("--", "–")
    return s


def main() -> int:
    rows = []
    for ln in TSV.read_text().splitlines():
        if not ln or ln.startswith("#"):
            continue
        parts = ln.split("\t")
        if len(parts) != 9:
            print(f"bad row ({len(parts)} fields): {ln[:80]}", file=sys.stderr)
            return 1
        rows.append(dict(zip("num cat name approach rationale session witness revival status".split(), parts)))
    rows.sort(key=lambda r: int(r["num"]))
    nums = [int(r["num"]) for r in rows]
    assert nums == list(range(1, len(rows) + 1)), "numbers must be 1..N contiguous"
    entries = [r for r in rows if r["cat"] != "--"]
    witnessed = [r for r in entries if r["witness"] not in ("—", "-", "")]
    revivable = [r for r in entries if r["revival"].isdigit() and int(r["revival"]) >= 2]
    unassigned = [r for r in rows if r["cat"] == "--"]

    # ---- LaTeX
    out = []
    out.append("%% GENERATED by tools/gen_dead_ends.py from tools/dead_ends.tsv — do not edit by hand.")
    out.append("\\renewcommand{\\arraystretch}{1.12}\\small")
    out.append("\\begin{longtable}{@{}p{0.55cm}p{3.1cm}p{4.35cm}p{5.4cm}@{}}")
    out.append("\\toprule \\textbf{\\#} & \\textbf{Dead end} & \\textbf{Approach} & \\textbf{Why it fails} \\\\ \\midrule \\endfirsthead")
    out.append("\\toprule \\textbf{\\#} & \\textbf{Dead end} & \\textbf{Approach} & \\textbf{Why it fails} \\\\ \\midrule \\endhead")
    out.append("\\midrule \\multicolumn{4}{r}{\\emph{continued on next page}} \\\\ \\endfoot")
    out.append("\\bottomrule \\endlastfoot")
    for code, title, gloss in CATS:
        group = [r for r in rows if r["cat"] == code]
        if not group:
            continue
        if code == "--":
            nums_ = ", ".join(r["num"] for r in group)
            out.append(f"\\multicolumn{{4}}{{@{{}}p{{13.4cm}}@{{}}}}{{\\textsc{{{title}}} ({len(group)}): "
                       f"\\emph{{{gloss}}}: \\#{nums_}.}} \\\\")
            continue
        out.append(f"\\multicolumn{{4}}{{@{{}}p{{13.4cm}}@{{}}}}{{\\textsc{{{title}}} ({code}, {len(group)} entries) --- \\emph{{{gloss}}}.}} \\\\[2pt]")
        for r in group:
            wname = r["witness"].replace("_", "\\_")
            wit = "" if r["witness"] in ("—", "-", "") else f" \\newline {{\\footnotesize\\color{{leanink}}$\\checkmark$\\,\\code{{{wname}}}}}"
            rev = "" if r["revival"] in ("-", "") else f" {{\\footnotesize[revival {r['revival']}]}}"
            sess = "" if r["session"] in ("-", "") else f" {{\\footnotesize(S{r['session']})}}"
            out.append(f"{r['num']} & {r['name']}{sess}{rev} & {r['approach']} & {r['rationale']}{wit} \\\\")
        out.append("\\midrule")
    # remove trailing midrule
    if out[-1] == "\\midrule":
        out.pop()
    out.append("\\end{longtable}")
    out.append("\\renewcommand{\\arraystretch}{1.0}\\normalsize")
    (ROOT / "paper" / "dead_ends_table.tex").write_text("\n".join(out) + "\n")

    stats = [
        "%% GENERATED by tools/gen_dead_ends.py",
        f"\\newcommand{{\\DEnumbers}}{{{len(rows)}}}",
        f"\\newcommand{{\\DEentries}}{{{len(entries)}}}",
        f"\\newcommand{{\\DEwitnessed}}{{{len(witnessed)}}}",
        f"\\newcommand{{\\DErevivable}}{{{len(revivable)}}}",
        f"\\newcommand{{\\DEunassigned}}{{{len(unassigned)}}}",
    ]
    (ROOT / "paper" / "dead_ends_stats.tex").write_text("\n".join(stats) + "\n")

    # ---- Markdown mirror
    md = ["# Dead ends — complete catalogue (generated from tools/dead_ends.tsv)", "",
          f"{len(rows)} numbers, {len(entries)} entries, {len(witnessed)} with a Lean witness, "
          f"{len(revivable)} with weak-MC revival score ≥ 2, {len(unassigned)} numbers never assigned.", ""]
    for code, title, gloss in CATS:
        group = [r for r in rows if r["cat"] == code]
        if not group:
            continue
        md.append(f"## {title} ({code}) — {md_from_tex(gloss)}")
        md.append("")
        if code == "--":
            md.append("Numbers: " + ", ".join("#" + r["num"] for r in group))
            md.append("")
            continue
        md.append("| # | Dead end | Session | Approach | Why it fails | Witness | Revival | Status |")
        md.append("|---|---|---|---|---|---|---|---|")
        for r in group:
            md.append("| " + " | ".join([r["num"], md_from_tex(r["name"]), r["session"], md_from_tex(r["approach"]),
                                        md_from_tex(r["rationale"]), ("`" + r["witness"] + "`") if r["witness"] not in ("—", "-", "") else "—",
                                        r["revival"], md_from_tex(r["status"])]) + " |")
        md.append("")
    (ROOT / "docs" / "dead_ends_catalog.md").write_text("\n".join(md) + "\n")

    # ---- Lean registry docstring block (between markers)
    lean_path = ROOT / "EM" / "Meta" / "DeadEnds.lean"
    lean = lean_path.read_text()
    b, e = "<!-- BEGIN GENERATED CATALOGUE -->", "<!-- END GENERATED CATALOGUE -->"
    if b in lean and e in lean:
        blk = [b, "", f"{len(rows)} numbers; {len(entries)} catalogued entries; {len(witnessed)} with a genuine Lean witness; "
               f"{len(revivable)} with revival score ≥ 2; unassigned numbers: "
               + ", ".join('#' + r['num'] for r in unassigned) + ".", ""]
        def md_cell(x):
            return md_from_tex(x).replace("|", "\\|")
        for code, title, gloss in CATS:
            group = [r for r in rows if r["cat"] == code]
            if not group or code == "--":
                continue
            blk.append(f"### {title} ({code}, {len(group)}) — {md_from_tex(gloss)}")
            blk.append("| # | Dead end | S | Why it fails | Witness | Rev |")
            blk.append("|---|---|---|---|---|---|")
            for r in group:
                w = ("`" + r["witness"] + "`") if r["witness"] not in ("—", "-", "") else "—"
                blk.append(f"| {r['num']} | {md_cell(r['name'])} | {r['session']} | {md_cell(r['rationale'])} | {w} | {r['revival']} |")
            blk.append("")
        blk.append(e)
        new = lean[:lean.index(b)] + "\n".join(blk) + lean[lean.index(e) + len(e):]
        lean_path.write_text(new)
    else:
        print("warning: catalogue markers not found in EM/Meta/DeadEnds.lean", file=sys.stderr)

    print(f"numbers={len(rows)} entries={len(entries)} witnessed={len(witnessed)} revivable={len(revivable)} unassigned={len(unassigned)}")
    by_cat = {c: sum(1 for r in rows if r['cat'] == c) for c, _, _ in CATS}
    print("by category:", by_cat)
    return 0


if __name__ == "__main__":
    sys.exit(main())
