#!/usr/bin/env python3
"""Generate paper/codebase_table.tex and paper/codebase_stats.tex.

Line counts come from `wc -l` on the live tree; descriptions and grouping
come from tools/codebase_table.tsv (group <TAB> file <TAB> LaTeX description).
Warns if the TSV and the set of active .lean files under EM/ (excluding
EM/Archive/) disagree. Run from the repo root:  python3 tools/gen_codebase_table.py
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TSV = ROOT / "tools" / "codebase_table.tsv"


def main() -> int:
    rows = []  # (group, file, desc)
    for ln in TSV.read_text().splitlines():
        if not ln or ln.startswith("#"):
            continue
        group, file, desc = ln.split("\t")
        rows.append((group, file, desc))

    active = set()
    for p in (ROOT / "EM").rglob("*.lean"):
        rel = p.relative_to(ROOT / "EM")
        if rel.parts[0] == "Archive":
            continue
        active.add(str(rel))

    listed = {f for _, f, _ in rows}
    ok = True
    for f in sorted(listed - active):
        print(f"WARNING: in TSV but not on disk: EM/{f}", file=sys.stderr)
        ok = False
    for f in sorted(active - listed):
        print(f"WARNING: on disk but not in TSV: EM/{f}", file=sys.stderr)
        ok = False

    counts = {f: len((ROOT / "EM" / f).read_text().splitlines())
              for _, f, _ in rows if (ROOT / "EM" / f).is_file()}
    total_lines = sum(counts.values())
    n_files = len(counts)

    archive_files = [p for p in (ROOT / "EM").rglob("*.lean")
                     if p.relative_to(ROOT / "EM").parts[0] == "Archive"]
    all_lines = total_lines + sum(len(p.read_text().splitlines()) for p in archive_files)
    all_files = n_files + len(archive_files)

    out = []
    out.append("%% AUTO-GENERATED by tools/gen_codebase_table.py — do not edit by hand.")
    out.append("%% Descriptions live in tools/codebase_table.tsv.")
    out.append(r"\begin{longtable}{l p{7cm} r}")
    out.append(r"\toprule")
    out.append(r"\textbf{File} & \textbf{Content} & \textbf{Lines} \\")
    out.append(r"\midrule")
    out.append(r"\endfirsthead")
    out.append(r"\toprule")
    out.append(r"\textbf{File} & \textbf{Content} & \textbf{Lines} \\")
    out.append(r"\midrule")
    out.append(r"\endhead")
    out.append(r"\midrule")
    out.append(r"\multicolumn{3}{r}{\emph{continued on next page}} \\")
    out.append(r"\endfoot")
    out.append(r"\bottomrule")
    out.append(r"\endlastfoot")
    prev_group = None
    for group, file, desc in rows:
        if group != prev_group:
            if prev_group is not None:
                out.append(r"\midrule")
            out.append(r"\multicolumn{3}{l}{\emph{%s}} \\" % group)
            prev_group = group
        latex_file = file.replace("_", r"\_")
        out.append(r"\code{%s} & %s & %d \\" % (latex_file, desc, counts[file]))
    out.append(r"\end{longtable}")
    (ROOT / "paper" / "codebase_table.tex").write_text("\n".join(out) + "\n")

    stats = [
        "%% AUTO-GENERATED by tools/gen_codebase_table.py — do not edit by hand.",
        r"\newcommand{\EMFileCount}{%d}" % n_files,
        r"\newcommand{\EMLineCount}{%s}" % f"{total_lines:,}".replace(",", r"{,}"),
        r"\newcommand{\EMFileCountAll}{%d}" % all_files,
        r"\newcommand{\EMLineCountAll}{%s}" % f"{all_lines:,}".replace(",", r"{,}"),
    ]
    (ROOT / "paper" / "codebase_stats.tex").write_text("\n".join(stats) + "\n")

    print(f"{n_files} files / {total_lines:,} lines active; "
          f"{all_files} / {all_lines:,} incl. Archive")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
